name: .NET Core Build & Test

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of the service/repository being built (used for path).'
        required: true
        type: string
      dotnet_version:
        description: 'The .NET SDK version to use.'
        required: true
        type: string
      solution_file_path:
        description: 'Path to the solution file for testing.'
        required: false
        type: string
        default: './'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Fetch depth 0 is required for SonarScanner to analyze all history
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Install Dependencies
        run: dotnet restore ${{ inputs.service_name }}/${{ inputs.service_name }}.csproj

      - name: Build Project
        run: dotnet build ${{ inputs.service_name }}/${{ inputs.service_name }}.csproj --configuration Release --no-restore
        
      - name: Run Tests & Collect Coverage
        run: |
          dotnet test ${{ inputs.solution_file_path }} \
            --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput='${{ github.workspace }}/coverage/' \
            --no-build \
            --logger trx \
            --results-directory "TestResults"