name: SonarQube Analysis

on:
  workflow_call:
    secrets:
        SONAR_TOKEN:
            description: 'SonarQube/SonarCloud analysis token.'
            required: true

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
